---
baseURL: https://mywebsite-hugo.vercel.app/
languageCode: en-us
title: Vimarsh
theme: PaperMod

relativeURLs: true
# description: A 17 Y/o Maker &amp; Learner
params:
  env: production
  title: Vimarsh
  description: A 17 Y/o Maker & Learner
  keywords:
  - Blog
  - Learner
  - Maker
  - Tech
  author: Vimarsh
  images:
  - "/uploads/profilepic.png"
  DateFormat: January 2, 2006
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    disableFingerprinting: true
  homeInfoParams:
    Title: Vimarsh
    Content: A 17 Y/o Maker & Learner.
  socialIcons:
  - name: github
    url: https://github.com/vimarsh244
  - name: twitter
    url: https://twitter.com/vimarsh244
  - name: email
    url: mailto:hi@vimarsh.info
  - name: linkedin
    url: https://www.linkedin.com/in/vimarshshah/
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
outputs:
  home:
  - HTML
  - RSS
  - JSON
menu:
  main:
  - identifier: about
    name: About
    url: "/about/"
    weight: "1"
  - identifier: posts
    name: Posts
    url: "/posts/"
    weight: "5"
  - identifier: notes
    name: Notes
    url: "/notes/"
    weight: "2"
  - identifier: projects
    name: Projects
    url: "/projects/"
    weight: "3"
  - identifier: search
    name: Search
    url: "/search/"
    weight: "7"
  - identifier: archive
    name: Archive
    url: "/archive/"
    weight: "4"
  - identifier: privacy
    name: Privacy
    url: "/privacy/"
    weight: "5"
